@echo off
echo Starting Telegram Bot...
echo Setting BOT_TOKEN...
set BOT_TOKEN=8527984904:AAEZSOQ25RMpyRcsYEy1TWxiYeEbZfzDqHY
echo Using venv_gpu Python...
"c:/Cursor Project/venv_gpu/Scripts/python.exe" telegram_bot.py
pause


